"""Initial database schema with all tables

Revision ID: 0a8702210b54
Revises: 
Create Date: 2025-11-01 21:14:15.011096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a8702210b54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('seasons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seasons_is_active'), 'seasons', ['is_active'], unique=False)
    op.create_index(op.f('ix_seasons_year'), 'seasons', ['year'], unique=False)
    op.create_table('matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='match_status'), nullable=False),
    sa.Column('rsvp_deadline', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_date'), 'matches', ['match_date'], unique=False)
    op.create_index(op.f('ix_matches_season_id'), 'matches', ['season_id'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('player_season_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('current_rating', sa.Float(), nullable=False),
    sa.Column('matches_completed', sa.Integer(), nullable=False),
    sa.Column('matches_attended', sa.Integer(), nullable=False),
    sa.Column('rating_locked', sa.Boolean(), nullable=False),
    sa.Column('last_calculated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('current_rating >= 1.0 AND current_rating <= 5.0', name='ck_rating_range'),
    sa.CheckConstraint('matches_attended <= matches_completed', name='ck_attendance_count'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season_id', name='uq_player_season')
    )
    op.create_index(op.f('ix_player_season_ratings_player_id'), 'player_season_ratings', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_season_ratings_season_id'), 'player_season_ratings', ['season_id'], unique=False)
    op.create_table('match_attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('rsvp_status', sa.Enum('PENDING', 'CONFIRMED', 'DECLINED', name='rsvp_status'), nullable=False),
    sa.Column('rsvp_at', sa.DateTime(), nullable=True),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player_attendance')
    )
    op.create_index(op.f('ix_match_attendances_match_id'), 'match_attendances', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_attendances_player_id'), 'match_attendances', ['player_id'], unique=False)
    op.create_table('player_match_ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('season_id', sa.UUID(), nullable=False),
    sa.Column('match_number', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('attended_match', sa.Boolean(), nullable=False),
    sa.Column('attended_third_time', sa.Boolean(), nullable=False),
    sa.Column('match_result', sa.Enum('WIN', 'DRAW', 'LOSS', 'DID_NOT_ATTEND', name='match_result_outcome'), nullable=False),
    sa.Column('team_average_rating', sa.Float(), nullable=True),
    sa.Column('opponent_average_rating', sa.Float(), nullable=True),
    sa.Column('rating_before', sa.Float(), nullable=False),
    sa.Column('rating_after', sa.Float(), nullable=False),
    sa.Column('rating_change', sa.Float(), nullable=False),
    sa.Column('elo_k_factor', sa.Float(), nullable=False),
    sa.Column('attendance_bonus', sa.Float(), nullable=False),
    sa.Column('third_time_bonus', sa.Float(), nullable=False),
    sa.Column('non_attendance_penalty', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('match_number > 0', name='ck_match_number_positive'),
    sa.CheckConstraint('rating_after >= 1.0 AND rating_after <= 5.0', name='ck_rating_after_range'),
    sa.CheckConstraint('rating_before >= 1.0 AND rating_before <= 5.0', name='ck_rating_before_range'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'match_id', name='uq_player_match_rating')
    )
    op.create_index(op.f('ix_player_match_ratings_match_date'), 'player_match_ratings', ['match_date'], unique=False)
    op.create_index(op.f('ix_player_match_ratings_match_id'), 'player_match_ratings', ['match_id'], unique=False)
    op.create_index(op.f('ix_player_match_ratings_player_id'), 'player_match_ratings', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_match_ratings_season_id'), 'player_match_ratings', ['season_id'], unique=False)
    op.create_index('ix_player_season_match_date_desc', 'player_match_ratings', ['player_id', 'season_id', 'match_date'], unique=False, postgresql_ops={'match_date': 'DESC'})
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Enum('TEAM_A', 'TEAM_B', name='team_name'), nullable=False),
    sa.Column('average_skill_rating', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'name', name='uq_match_team_name')
    )
    op.create_index(op.f('ix_teams_match_id'), 'teams', ['match_id'], unique=False)
    op.create_table('third_time_attendances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('attended', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id', 'player_id', name='uq_match_player_third_time')
    )
    op.create_index(op.f('ix_third_time_attendances_match_id'), 'third_time_attendances', ['match_id'], unique=False)
    op.create_index(op.f('ix_third_time_attendances_player_id'), 'third_time_attendances', ['player_id'], unique=False)
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('team_a_id', sa.UUID(), nullable=False),
    sa.Column('team_b_id', sa.UUID(), nullable=False),
    sa.Column('team_a_score', sa.Integer(), nullable=False),
    sa.Column('team_b_score', sa.Integer(), nullable=False),
    sa.Column('winning_team_id', sa.UUID(), nullable=True),
    sa.Column('result_type', sa.Enum('WIN', 'DRAW', name='result_type'), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['winning_team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_results_match_id'), 'match_results', ['match_id'], unique=True)
    op.create_table('team_players',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('player_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'player_id', name='uq_team_player')
    )
    op.create_index(op.f('ix_team_players_player_id'), 'team_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_team_players_team_id'), 'team_players', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_players_team_id'), table_name='team_players')
    op.drop_index(op.f('ix_team_players_player_id'), table_name='team_players')
    op.drop_table('team_players')
    op.drop_index(op.f('ix_match_results_match_id'), table_name='match_results')
    op.drop_table('match_results')
    op.drop_index(op.f('ix_third_time_attendances_player_id'), table_name='third_time_attendances')
    op.drop_index(op.f('ix_third_time_attendances_match_id'), table_name='third_time_attendances')
    op.drop_table('third_time_attendances')
    op.drop_index(op.f('ix_teams_match_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_player_season_match_date_desc', table_name='player_match_ratings', postgresql_ops={'match_date': 'DESC'})
    op.drop_index(op.f('ix_player_match_ratings_season_id'), table_name='player_match_ratings')
    op.drop_index(op.f('ix_player_match_ratings_player_id'), table_name='player_match_ratings')
    op.drop_index(op.f('ix_player_match_ratings_match_id'), table_name='player_match_ratings')
    op.drop_index(op.f('ix_player_match_ratings_match_date'), table_name='player_match_ratings')
    op.drop_table('player_match_ratings')
    op.drop_index(op.f('ix_match_attendances_player_id'), table_name='match_attendances')
    op.drop_index(op.f('ix_match_attendances_match_id'), table_name='match_attendances')
    op.drop_table('match_attendances')
    op.drop_index(op.f('ix_player_season_ratings_season_id'), table_name='player_season_ratings')
    op.drop_index(op.f('ix_player_season_ratings_player_id'), table_name='player_season_ratings')
    op.drop_table('player_season_ratings')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_season_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_match_date'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_seasons_year'), table_name='seasons')
    op.drop_index(op.f('ix_seasons_is_active'), table_name='seasons')
    op.drop_table('seasons')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
